---

stages:
  - prepare
  - build
  - release
  - trigger

prepare:stable:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull nginx:stable-alpine
  only:
    - master

prepare:stable:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull nginx:mainline-alpine
  only:
    - master

build:stable:
  stage: build
  tags:
    - dockerwest
  script:
    - cd stable; ./build.sh
  only:
    - master

build:mainline:
  stage: build
  tags:
    - dockerwest
  script:
    - cd mainline; ./build.sh
  only:
    - master

release:stable:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/nginx:stable
  only:
    - master

release:mainline:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/nginx:mainline
  only:
    - master

trigger:nginx-laravel:
  stage: trigger
  trigger:
    project: DockerWest/nginx-laravel

trigger:nginx-magento1:
  stage: trigger
  trigger:
    project: DockerWest/nginx-magento1

trigger:nginx-magento2:
  stage: trigger
  trigger:
    project: DockerWest/nginx-magento2

trigger:nginx-pimcore4:
  stage: trigger
  trigger:
    project: DockerWest/nginx-pimcore4

trigger:nginx-pimcore5:
  stage: trigger
  trigger:
    project: DockerWest/nginx-pimcore5

trigger:nginx-symfony3:
  stage: trigger
  trigger:
    project: DockerWest/nginx-symfony3

trigger:nginx-symfony4:
  stage: trigger
  trigger:
    project: DockerWest/nginx-symfony4
